import os
os.system("cls")

print("=======")
print("=SENAI=")
print("=======")

nome = input("Digite seu nome: ")
print("=======")
print("=SENAI=")
print("=======")
os.system("cls")
idade = int(input("Digite sua idade:"))
print("=======")
print("=SENAI=")
print("=======")
os.system("cls")
peso = float(input("Digite seu peso:"))
print("=======")
print("=SENAI=")
print("=======")

os.system("cls")
print("=======")
print("=SENAI=")
print("=======")
print(f"Nome: {nome}")
print(f"Idade: {idade}")
print(f"Peso: {peso}")